### ISSUE TITLE
Some coreutils e.g. md5sum or shaXYZsum necessary for makepkg are missing

### ISSUE THREAD

**Issue by nanoant** [archmac/bootstrap#2]
`makepkg` relies `md5sum` and `shaXYZsum` which come with `coreutils` Arch Linux package. macOS does not have this, but it has `md5` and `shasum` commands.

I can only suspect you have them on your system coming from somewhere. Right?

What if we have created wrappers for these commands e.g.:

`md5sum`
~~~bash
#!/bin/bash
exec /sbin/md5 -r "$@"
~~~

`sha1sum` (and same for `224`, `256`, `384`, `512`)
~~~bash
#!/bin/bash
exec /sbin/shasum -a 1 "$@"
~~~

And add them to some extra `coreutils-wrappers` or `coreutils-macos-wrappers` or whatever name that fits and make this a dependency for `pacman` on Arch Mac?

**Comment by lloeki** [comment]
I think I did not need them, at the time at least it was not a requirement and could use `md5` and `shasum` directly. There have been some changes though in pacman 5.1 where the check for supported algorithms hinges on command naming.

I later used such wrappers to work around that:

```
$ cat /Users/lloeki/.local/bin/sha256sum
#!/bin/sh

exec shasum -a 256 "$@"
```

I'd rather have the package be named `coreutils-sum-compat` unless you plan to have more `coreutils` compatibility tools.

Also I did not package them because the output differs slightly form coreutils, which would break some tools (not in our case, but if it's being packaged it has to be identical so as not to break expectations)

**Comment by lloeki** [comment]
I just added some `coreutils` with a `g` prefix.
